server:
  port: 8080

spring:
  application:
    name: spring-deepseek
  ai:
    openai:
      # 阿里百炼
      # 调用AI接口时表明身份的API Key
        api-key: sk-71dd5117c788f14a11969cf82da22b2348
      # 调用AI接口时的基础路径，配置的是阿里云百炼的基础路径
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        chat:
          options:
            # 调用的模型，DeepSeek的话可以选择deepseek-r1或deepseek-v3
            model: qwen-vl-max-latest # deepseek-r1
            # 用来控制文本生成的随机性（创造力），值越小越严谨
            temperature: 0.8
      # 智谱清言平台
#      api-key: 10768dd45edf451ca11086781f7f485c.71JjLQMVFpolPgguNG
#      base-url: https://open.bigmodel.cn/api/paas/v4/chat/completions
#      chat:
#        options:
#          # 调用的模型，DeepSeek的话可以选择deepseek-r1或deepseek-v3
#          model: glm-4v-flash
#          # 用来控制文本生成的随机性（创造力），值越小越严谨
#          temperature: 0.8
